# Generated by Django 4.0.6 on 2022-08-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sur_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(default='', max_length=300),
        ),
    ]
